# Generated by Django 3.1.4 on 2020-12-18 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='delivery_method',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='paymentscard',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='paymentscard',
            name='cvc_number',
        ),
        migrations.RemoveField(
            model_name='paymentscard',
            name='validation_code',
        ),
    ]
