<<<<<<< HEAD
# Generated by Django 3.1.4 on 2020-12-21 17:33
=======
# Generated by Django 3.1.4 on 2020-12-21 08:44
>>>>>>> 14180b79a2f88474d8654349a4d07aa951458829

from django.db import migrations, models
import django.db.models.deletion
import validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='emails')),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AddressList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('appartment_type', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200, validators=[validation.validate_city])),
<<<<<<< HEAD
                ('county_region', models.CharField(max_length=100)),
=======
                ('country_region', models.CharField(max_length=100)),
>>>>>>> 14180b79a2f88474d8654349a4d07aa951458829
                ('postcode', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50, validators=[validation.validate_phone])),
                ('company', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'address_list',
            },
        ),
    ]
