# Generated by Django 3.1.4 on 2020-12-18 08:20

from django.db import migrations, models
import django.db.models.deletion
import validation


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('appartment_type', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200, validators=[validation.validate_city])),
                ('county_region', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50, validators=[validation.validate_phone])),
                ('company', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'address_list',
            },
        ),
        migrations.AlterField(
            model_name='addresses',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='addresses',
            name='address_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.addresslist'),
        ),
    ]
