# Generated by Django 3.1.4 on 2020-12-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201218_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.addresslist'),
        ),
    ]
