<<<<<<< HEAD:orders/migrations/0002_auto_20201222_0233.py
# Generated by Django 3.1.4 on 2020-12-21 17:33
=======
# Generated by Django 3.1.4 on 2020-12-21 08:44
>>>>>>> 14180b79a2f88474d8654349a4d07aa951458829:orders/migrations/0002_auto_20201221_1744.py

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:orders/migrations/0002_auto_20201222_0233.py
        ('users', '0001_initial'),
        ('payments', '0001_initial'),
        ('orders', '0001_initial'),
=======
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
        ('payments', '0001_initial'),
>>>>>>> 14180b79a2f88474d8654349a4d07aa951458829:orders/migrations/0002_auto_20201221_1744.py
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payments'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='options',
<<<<<<< HEAD:orders/migrations/0002_auto_20201222_0233.py
            name='option',
            field=models.ManyToManyField(through='orders.ProductOption', to='products.Products'),
=======
            name='optionkilograms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.optionkilograms'),
        ),
        migrations.AddField(
            model_name='options',
            name='optionpieces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.optionpieces'),
        ),
        migrations.AddField(
            model_name='options',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
>>>>>>> 14180b79a2f88474d8654349a4d07aa951458829:orders/migrations/0002_auto_20201221_1744.py
        ),
        migrations.AddField(
            model_name='carts',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.options'),
        ),
        migrations.AddField(
            model_name='carts',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='carts',
            name='payments_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentstype'),
        ),
        migrations.AddField(
            model_name='carts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
