# Generated by Django 3.1.4 on 2020-12-16 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
        ('products', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='payments.payments'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payments_types',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentstype'),
        ),
        migrations.AddField(
            model_name='orders',
            name='users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='carts',
            name='orders',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='carts',
            name='payments_types',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentstype'),
        ),
        migrations.AddField(
            model_name='carts',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AddField(
            model_name='carts',
            name='users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
