# Generated by Django 3.1.4 on 2020-12-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
        ('payments', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payments'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='options',
            name='optionkilograms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.optionkilograms'),
        ),
        migrations.AddField(
            model_name='options',
            name='optionpieces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.optionpieces'),
        ),
        migrations.AddField(
            model_name='options',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AddField(
            model_name='carts',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.options'),
        ),
        migrations.AddField(
            model_name='carts',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='carts',
            name='payments_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentstype'),
        ),
        migrations.AddField(
            model_name='carts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
