# Generated by Django 3.1.3 on 2020-12-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201222_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='sub_total',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carts',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
