# Generated by Django 3.1.4 on 2020-12-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201217_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
