# Generated by Django 3.1.4 on 2020-12-18 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201217_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='discount_code',
        ),
    ]
