# Generated by Django 3.1.4 on 2020-12-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201219_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total_cost',
        ),
    ]
