# Generated by Django 3.1.4 on 2020-12-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201222_1254'),
        ('orders', '0002_auto_20201221_1744'),
    ]

    operations = [
    ]
