# Generated by Django 3.1.4 on 2020-12-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagesproducts',
            table='images_products',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
